### ISSUE TITLE
Exporter crashes when used multiple times in a pepper session

### ISSUE THREAD

**Issue by MartinKl** [korpling/pepperModules-RelANNISModules#3]
I used the RelANNISExporter (1.1.7-SNAPSHOT provided with pepper_full from 2014-11-12) with pepper_full from 2014-10-24. Converting some data for the first time, no errors occur. But running a second conversion throws the following:

CONVERSION ENDED WITH ERRORS, REQUIRED TIME: 4 s
   Error in Pepper module 'RelANNISExporter, 1.1.7.SNAPSHOT', please contact the module supplier.  (PepperModuleExceptio
   n)
full stack trace:
de.hu_berlin.german.korpling.saltnpepper.pepper.modules.exceptions.PepperModuleException: Error in Pepper module 'RelANNISExporter, 1.1.7.SNAPSHOT', please contact the module supplier. 
    at de.hu_berlin.german.korpling.saltnpepper.pepperModules.relannis.RelANNISExporter.start(RelANNISExporter.java:226)
    at de.hu_berlin.german.korpling.saltnpepper.pepper.modules.impl.PepperModuleImpl.start(PepperModuleImpl.java:529)
    at de.hu_berlin.german.korpling.saltnpepper.pepper.modules.impl.PepperExporterImpl.start(PepperExporterImpl.java:98)
    at de.hu_berlin.german.korpling.saltnpepper.pepper.core.ModuleControllerImpl$2.run(ModuleControllerImpl.java:246)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: de.hu_berlin.german.korpling.saltnpepper.misc.relANNIS.exceptions.RelANNISException: Cannot save more than one content objects (RACorpusGraph-objects) per resource. In this case '2' resources: [[RACorpusGraphImpl(null): ], [RACorpusGraphImpl(null): ]].
    at de.hu_berlin.german.korpling.saltnpepper.misc.relANNIS.resources.RelANNISResource.save(RelANNISResource.java:169)
    at de.hu_berlin.german.korpling.saltnpepper.pepperModules.relannis.RelANNISExporter.start(RelANNISExporter.java:203)
    ... 8 more

This error does not occur when pepper is restarted first (by saying "exit" and relaunching it).

**Comment by FlorianZipser** [comment]
This should be solved in new relANNIS 4 Exporter
